  
# data

data_dir:
  value: "C:/DL_Lab/GBR_dataset/" #"/content/"
val_split:
  value: 0.2
test_split:
  value: 0.2
augment_crop:
  value: 450
number_of_bboxes:
  value: 18
img_width:
  value: 1280
img_height:
  value: 720
balancing:  # oversampling
  value: True

# train
epochs:
  value: 200
batch_size:
  value: 8
optimizer:
  value: "sgd"
learning_rate:
  value: 0.01
learning_rate_decay:
  value: 100
momentum:
  value: 0.9

# architecture
cnn_input_shape:
  value: [448, 448, 3]
architecture:
  value: "resnet50" 
grid_size:
  value: 7
  