  
# data

data_dir:
  value: "C:/DL_Lab/GBR_dataset/" #"/content/"
val_split:
  value: 0.2
test_split:
  value: 0.2
img_width:
  value: 1280
img_height:
  value: 720
dataset_slice_start:
  value: 0  # 20
dataset_slice_end:
  value: 23500  # 180


# train
epochs:
  value: 100
batch_size:
  value: 128
optimizer:
  value: "sgd"
learning_rate:
  value: 0.01
learning_rate_decay:
  value: 10
momentum:
  value: 0.9

# architecture
cnn_input_shape:
  value: [448, 448, 3]
architecture:
  value: "resnet50" 
grid_size:
  value: 7
  